# Server port
server.port=9095

# DataSource configuration
spring.datasource.url=${SNOWFLAKE_JAVA_URL}
spring.datasource.username=${SNOWFLAKE_JAVA_USERNAME}
spring.datasource.password=${SNOWFLAKE_JAVA_PASSWORD}
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver

# JPA settings (Hibernate is optional with Snowflake)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
